# Generated by Django 3.1 on 2021-09-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210912_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('colour', 'kalar'), ('size', 'sayaz')], max_length=100),
        ),
    ]
